# Reshape In Numpy - 2

### Reshape function in NumPy is used to change the shape of an ndarray.

In [9]:
import numpy as np

In [10]:
arr = np.array([[12, 10, 10, 20, 30], [45, 34, 56, 34, 23]])

In [11]:
arr

array([[12, 10, 10, 20, 30],
       [45, 34, 56, 34, 23]])

In [12]:
new_arr = arr.reshape(-1)

In [14]:
new_arr.ndim

1

In [15]:
-new_arr.shape

(10,)

# 3d -->  1d

In [20]:
xyz = np.array([[[12, 10, 90, 10], [23, 10, 90, 78]], [[23, 10, 90, 78], [45, 23, 12, 34]]])


In [22]:
xyz.ndim

3

In [23]:
xyz.shape

(2, 2, 4)

In [24]:
xyz

array([[[12, 10, 90, 10],
        [23, 10, 90, 78]],

       [[23, 10, 90, 78],
        [45, 23, 12, 34]]])

In [25]:
new_xyz = xyz.reshape(-1)

In [26]:
new_xyz

array([12, 10, 90, 10, 23, 10, 90, 78, 23, 10, 90, 78, 45, 23, 12, 34])

# 3d --> 2d

In [28]:
xyz = np.array([[[12, 10, 90, 10], [23, 10, 90, 78]], [[23, 10, 90, 78], [45, 23, 12, 34]]])


In [34]:
new = xyz.reshape(-1, 4)

In [35]:

new

array([[12, 10, 90, 10],
       [23, 10, 90, 78],
       [23, 10, 90, 78],
       [45, 23, 12, 34]])

In [45]:
arr = np.array([12, 10, 20, 89, 10, 200, 90, 89, 90])

In [46]:
newarr = arr.reshape(3, -1)

In [47]:
newarr

array([[ 12,  10,  20],
       [ 89,  10, 200],
       [ 90,  89,  90]])