# Slicing In Numpy Array

# slicing:   [start : end : increment]

In [ ]:
[start : end : increment]

default values:
start : 0
end = n - 1
increment = 1

In [1]:

import numpy as np

In [2]:
arr = np.array([12, 10, 10, 20, 39, 89])

In [5]:
arr[1 : 5 : 1]

array([10, 10, 20, 39])

In [8]:
arr1 = np.array([[12, 10, 90, 100, 90], [34, 10, 78, 80, 78]])

In [10]:
arr1.ndim

2

In [13]:
arr1[1, 1 : 4]

array([10, 78, 80])

In [15]:
arr1[0, 2 : ]

array([ 90, 100,  90])

In [20]:
arr2 = np.array([[[12, 10, 90, 100, 90], [34, 10, 78, 80, 78]], [[30, 89, 56, 23, 54], [23, 56, 23, 34, 23]]])

In [21]:
arr2.ndim

3

In [22]:
arr2

array([[[ 12,  10,  90, 100,  90],
        [ 34,  10,  78,  80,  78]],

       [[ 30,  89,  56,  23,  54],
        [ 23,  56,  23,  34,  23]]])

In [26]:
arr2[0, 1, 1 : 4]

array([10, 78, 80])

In [30]:
arr2[1, 0, 1 : ]

array([89, 56, 23, 54])