                                              Dimensions in Arrays

In [ ]:
ndarray

array()

In [2]:
import numpy as np

In [3]:
arr = np.array(20)

In [6]:
arr

array(20)

In [7]:
# ndim

In [8]:
arr = np.array(20)

In [9]:
arr.ndim

0

In [10]:
abc = np.array([12, 10, 90, 10])

In [11]:
abc

array([12, 10, 90, 10])

In [12]:
abc.ndim

1

In [18]:
xyz = np.array([[12, 10, 90], [45, 50, 30]])

In [19]:
xyz

array([[12, 10, 90],
       [45, 50, 30]])

In [20]:
xyz.ndim

2

In [24]:
xy = np.array([[[12, 10, 90], [45, 50, 30]], [[12, 10, 100], [23, 10, 89]]])

In [25]:
xy

array([[[ 12,  10,  90],
        [ 45,  50,  30]],

       [[ 12,  10, 100],
        [ 23,  10,  89]]])

In [26]:
xy.ndim

3