## Searching element's index number in Arrays 

In [4]:
import numpy as np

In [5]:
arr = np.array([12, 34, 23, 12, 1, 67, 45, 3, 45, 67, 34, 23])

In [6]:
arr

array([12, 34, 23, 12,  1, 67, 45,  3, 45, 67, 34, 23])

In [7]:
arr.ndim

1

In [8]:
arr.shape

(12,)

In [9]:
arr = np.array([12, 34, 23, 12, 1, 67, 45, 3, 45, 67, 34, 23])

In [ ]:
# where()

In [13]:
np.where(arr == 45)

(array([6, 8], dtype=int64),)

In [14]:
np.where(arr%2 == 0)

(array([ 0,  1,  3, 10], dtype=int64),)