# Reshape In Numpy 

### Reshape function in NumPy is used to change the shape of an ndarray.

In [68]:
import numpy as np

In [69]:
arr = np.array([12, 10, 90, 78, 56, 19, 78, 67, 34, 10])

In [71]:
arr.shape

(10,)

In [72]:
# 2d => (rows, column)

In [73]:
new_arr = arr.reshape(2, 5)

In [74]:
new_arr

array([[12, 10, 90, 78, 56],
       [19, 78, 67, 34, 10]])

In [75]:
new_arr = arr.reshape(5, 2)

In [76]:
new_arr

array([[12, 10],
       [90, 78],
       [56, 19],
       [78, 67],
       [34, 10]])

In [79]:
# new_arr = arr.reshape(3, 3)

# 1d to 3d

In [80]:
x = np.array([12, 10, 90, 78, 56, 19, 78, 67, 34, 10, 12, 10])

In [84]:
x.shape

(12,)

In [81]:
x.ndim

1

In [83]:
# 3d =>  (depth, rows, columns)

In [85]:
x_new = x.reshape(2, 2, 3)

In [86]:
x_new

array([[[12, 10, 90],
        [78, 56, 19]],

       [[78, 67, 34],
        [10, 12, 10]]])